services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  app:
    build: .
    container_name: ml-summarizer-app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    restart: unless-stopped
volumes: 
  ollama_data:
    name: ollama_data
