services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  
  ollama-setup:
    image: ollama/ollama:latest
    container_name: ollama-setup
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      ollama:
        condition: service_healthy
    command: >
      sh -c "ollama pull rouge/phi-3.5-mini-4k-instruct"

  app:
    build: .
    container_name: ml-summarizer-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - PHI_MODEL_NAME=rouge/phi-3.5-mini-4k-instruct
      - NLLB_MODEL_NAME=facebook/nllb-200-distilled-600M
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "python","/app/healthcheck.py"]
      interval: 300s
      timeout: 3s
      retries: 5
volumes: 
  ollama_data:
    name: ollama_data
